FROM golang:1.23 AS builder
WORKDIR /app
ENV CGO_ENABLED=0
ENV GOOS=linux

COPY . .

RUN go build -o bin -mod=readonly cmd/client/main.go

FROM scratch

WORKDIR /app
COPY --from=builder /app/bin /app/bin
COPY --from=builder /app/config/client_docker.json /app/config.json

ENTRYPOINT ["./bin"]
