FROM golang:1.23-alpine AS builder
WORKDIR /app
ENV CGO_ENABLED=0
ENV GOOS=linux

COPY . .

RUN go build -o bin -mod=readonly cmd/server/main.go

FROM scratch

ARG POW_SERVER_DEBUG
ARG POW_SEVER_CONFIG_PATH

ENV POW_DEBUG=$POW_SERVER_DEBUG
ENV POW_CONFIG_PATH=$POW_SEVER_CONFIG_PATH

WORKDIR /app
COPY --from=builder /app/bin /app/bin
COPY --from=builder /app/config/server.json /app/server.json

ENTRYPOINT ["./bin"]
