FROM golang:1.23-alpine AS builder
WORKDIR /app
ENV CGO_ENABLED=0
ENV GOOS=linux

COPY . .

RUN go build -o bin -mod=readonly cmd/client/main.go

FROM scratch

ARG POW_DEBUG
ARG POW_CONFIG_PATH

ENV POW_DEBUG=$POW_DEBUG
ENV POW_CONFIG_PATH=$POW_CONFIG_PATH

WORKDIR /app
COPY --from=builder /app/bin /app/bin
COPY --from=builder /app/config/server.json /app/server.json

ENTRYPOINT ["./bin"]
